spring:
  application:
    name: MetricsProducerApplication

#Настройка Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always