spring:
  application:
    name: MetricsProducerApplication
server:
  port: 8080

#Настройка Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always